packages:
  - 'apps/*'
  - 'services/*'
  - 'tests/*'
allowBuilds:
  '@playwright/browser-chromium': true
  '@sentry/capacitor': true
  '@swc/core': true
  cypress: true
  esbuild: true
  protobufjs: true
  unix-dgram: true
