apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
    name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  revisionHistoryLimit: 0
  strategy:
    type: Recreate
  selector:
    matchLabels:
      name: {{ .Release.Name }}
  template:
    metadata:
      labels:
        name: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Release.Name }}
          image: {{ printf "%s:%s" .Values.image.repository .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            {{- toYaml .Values.envs | nindent 12 }}
            - name: MONGO_URL
              value: {{ if .Values.mongodb.enabled }}{{ printf "%s-mongodb.%s.svc.cluster.local" .Release.Name .Release.Namespace }}{{ else }}{{ .Values.external.mongoURL }}{{ end }}
            - name: RABBITMQ_URL
              value: {{ if .Values.rabbitmq.enabled }}{{ printf "%s-rabbitmq.%s.svc.cluster.local" .Release.Name .Release.Namespace }}{{ else }}{{ .Values.external.rabbitmqURL }}{{ end }}
          envFrom:
            - secretRef:
                name: {{ printf "%s-env-secrets" .Release.Name }}
          ports:
            - containerPort: {{ .Values.service.port }}
          readinessProbe:
            httpGet:
              path: /health/
              port: {{ .Values.service.port }}
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 10
            failureThreshold: 5
          livenessProbe:
            httpGet:
              path: /health/
              port: {{ .Values.service.port }}
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 10
            failureThreshold: 5
          startupProbe:
            httpGet:
              path: /health/
              port: {{ .Values.service.port }}
            initialDelaySeconds: 5
            periodSeconds: 2
            timeoutSeconds: 10
            failureThreshold: 20
          resources:
            {{ toYaml .Values.resources | nindent 12 }}
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              name: {{ .Release.Name }}
      restartPolicy: Always
